spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/test
      username: sa
      password:
      driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: true
    show-sql: true
    properties:
      hibernate:
        jdbc:
          batch_size: 300
        format_sql: true
    open-in-view: false
    generate-ddl: true
  h2:
    console:
      enabled: true